# Generated by Django 5.2.6 on 2025-10-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
